services:
  moodledb:
    image: mariadb:latest
    container_name: ${DOMAIN}_db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - TZ=America/Sao_Paulo
    networks:
      - default

  moodlepgdb: # 🛠 Corrigido nome duplicado e conflito com mariadb/postgres
    image: postgres:13
    container_name: ${DOMAIN}_pgdb
    restart: always
    volumes:
      - ./pg_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=America/Sao_Paulo
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    networks:
      - default

  campusvirtual2.com:
    container_name: ${DOMAIN}_web
    env_file: .env
    build: .
    ports:
      - '8002:80'
    environment:
      - MOODLE_DATABASE_TYPE=pgsql
      - MOODLE_DATABASE_HOST=moodlepgdb
      - MOODLE_DATABASE_PORT_NUMBER=5432
      - MOODLE_DATABASE_USER=${POSTGRES_USER}
      - MOODLE_DATABASE_NAME=${POSTGRES_DB}
      - MOODLE_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_REVERSEPROXY=yes
      - TZ=America/Sao_Paulo
      - PINPOINT_COLLECTOR_HOST=pinpoint-collector # 🆕 Necessário para agente PHP localizar o collector
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/99-custom.ini
      - ./moodle_data:/var/www/html
      - ./moodledata_data:/var/www/moodledata
      - ./logs:/var/log/apache2
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - moodlepgdb
    extra_hosts:
      - "${DOMAIN}:127.0.1.1"
    networks:
      - rede_proxy_reverso
      - default

  cron:
    image: moodlehq/moodle-php-apache:8.1
    container_name: ${DOMAIN}_cron
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ./moodle_data:/var/www/html
      - ./moodledata_data:/var/www/moodledata
    entrypoint: >
      /bin/sh -c "while true; do php /var/www/html/moodle/admin/cli/cron.php; sleep 60; done"
    depends_on:
      - campusvirtual2.com

  redis:
    image: redis:7.4.1-alpine
    container_name: ${DOMAIN}_redis
    volumes:
      - ./redis:/data
    command: >
      redis-server --save 900 1
                   --rename-command SLAVEOF ""
                   --rename-command REPLICAOF ""
                   --rename-command CONFIG ""
                   --dir /data
    restart: always
    networks:
      - default

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    environment:
      DB_MYSQL_HOST: moodledb
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm_user
      DB_MYSQL_PASSWORD: secure_npm_password
      DB_MYSQL_NAME: npm_database
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt
    networks:
      - rede_proxy_reverso
      - default

  moodle-backup:
    build:
      context: ./backup
    container_name: ${DOMAIN}_backup
    env_file: .env
    environment:
      - TZ=America/Sao_Paulo
      - POSTGRES_HOST=moodlepgdb
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_BUCKET_PATH=${AWS_BUCKET_PATH}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - ./backup:/backup
      - ./moodle_data:/var/www/html:ro
      - ./moodledata_data:/var/www/moodledata:ro
    restart: unless-stopped
    networks:
      - rede_proxy_reverso
      - default


volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local
  pg_data:
    driver: local

networks:
  default:
    name: rede_${DOMAIN}
  rede_proxy_reverso:
    name: rede_proxy_reverso_interna

