# Tuning baseado em 4 GB de RAM
listen_addresses = '*'
shared_buffers = 1GB
effective_cache_size = 3GB
work_mem = 16MB
maintenance_work_mem = 256MB
max_connections = 100
wal_buffers = 16MB
checkpoint_completion_target = 0.9
random_page_cost = 1.1
log_min_duration_statement = 500
log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '

# Reduz I/O excessivo
bgwriter_lru_maxpages = 100
bgwriter_lru_multiplier = 2.0
