# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /etc/letsencrypt/archive/campusvirtual2.com
cert = /etc/letsencrypt/live/campusvirtual2.com/cert.pem
privkey = /etc/letsencrypt/live/campusvirtual2.com/privkey.pem
chain = /etc/letsencrypt/live/campusvirtual2.com/chain.pem
fullchain = /etc/letsencrypt/live/campusvirtual2.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = bbd8b3806fd63e5e3db5af2affa5ecc7
authenticator = webroot
webroot_path = /opt/moodle-docker/moodle_data/moodle,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
campusvirtual2.com = /opt/moodle-docker/moodle_data/moodle
www.campusvirtual2.com = /opt/moodle-docker/moodle_data/moodle
